### ISSUE TITLE
Unable to open prefences menu (GNU/Linux)

### ISSUE THREAD

**Issue by theatre-x** [az0/bleachbit#91] opened 2015-06-18 15:12 UTC
Here's a funny bug!

I have tried replicating this in Windows but I can not for the life of me even try to figure out how to cause an Error 13.
On GNU/Linux, if you run BleachBit using the "BleachBit as Admin" option, set a directory that you do not have permission to wipe (I used the / directory), select the option to wipe the Free Disk Space, and run the cleaning process, you will get an Error 13.

After this, try to open BB's preferences menu.
It won't open.
You have to restart BleachBit.

I tested this using BB 1.6 on Linux Mint 17.1 and Trisquel 6 Mini.
I'm going to test this with BB 1.7 Beta.

**Comment by theatre-x** [comment] 2015-06-18 15:37
Yep, confirmed that this effects BB 1.7 Beta with Trisquel 6 Mini.

**Comment by az0** [comment] 2015-06-20 02:56
Shouldn't the root user have permissions to wipe /?  When I wipe the root directory as the root user, it wipes.  When I wipe the root directory as a normal user, I get error 13.

After I do this and start as a normal user, I can open the preferences.

In the configuration file (~/.config/bleachbit/bleachbit.ini) is a section that records the shredding path, and mine looks like this:
````
[list/shred_drives]
0 = /
````
There is one path defined, and it is the root directory.  Does yours look like this?

**Comment by theatre-x** [comment] 2015-06-23 01:31
I thought that was a bit strange.
I used the "Bleachbit as Administrator" option in the Gnome/Cinnamon menus.

I will have to check back on the affected machines tomorrow for I am not physically near them right now.
I will also do a desktop recording of the problem.
I recently upgraded one of the machines to 1.8 but the Trisquel one still uses 1.6.
I'll try with both.

**Comment by theatre-x** [comment] 2015-06-24 14:54
That's strange.
I don't seem to have the config file that you speak of.

Here is the error 13 that I get:

    [Errno 13] Permission denied: '/tmpFroprYYw0W_HWgERI5jY821YChxFKkyhSn.TbVNr0hYcLnFzlF-h4aEf4.ecg6U9BMsswOv7J_pY-W_CtWD0.0LVpCTEiH3YJ8g42zA3-7ASZIo0QS-sXzYohxs--gRMCOG-b.A__VQvDNqhkl76Ths19Z7BR-CCXV1-Bok.SwcLEmBMZV7DraqLgvZmv9Li.mKnuB.60ZWIutqa-GV-J51KLm-sqXp7tw94-4tFKPuP6qDXNcgPEPcQi2d'

This is also when I used BleachBit 1.6 as Admin and I have video showing the issue still occurs in 1.8.
I will upload the vid to YouTube ASAP.

**Comment by az0** [comment] 2015-07-09 03:21
> I don't seem to have the config file that you speak of.

Weird. When you start BleachBit, click **Help - System Information**, and look for a line like this

> options_dir = /home/username/.config/bleachbit

This line should give you the directory that holds `bleachbit.ini`

Next, is the

**Comment by Krak-n** [comment] 2015-07-23 18:15
I am also unable to reproduce this issue using @az0's steps above. Root should have permissions to delete anything on the system.

See [this](https://unix.stackexchange.com/questions/2459/how-to-create-a-file-even-root-user-cant-delete-it) article.

**Comment by az0** [comment] 2016-01-17 22:36
This bug seems not reproducible, so I am closing it. If it comes up, feel free to reopen this bug ticket or open a new one.

**Closed by az0** 2016-01-17 22:36 UTC
Labels: bug, not reproduced
